//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int cthd_id { get; set; }
        public int cthd_masp { get; set; }
        public int cthd_mahd { get; set; }
        public int cthd_soluong { get; set; }
        public double cthd_giatien { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual hoadon hoadon { get; set; }
    }
}
