//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdondat
    {
        public int ctdd_id { get; set; }
        public int ctdd_madd { get; set; }
        public int ctdd_masp { get; set; }
        public int ctdd_soluong { get; set; }
        public double ctdd_giatien { get; set; }
    
        public virtual dondat dondat { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
