//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dondat()
        {
            this.chitietdondats = new HashSet<chitietdondat>();
        }
    
        public int dd_id { get; set; }
        public string dd_makh { get; set; }
        public int dd_matt { get; set; }
        public Nullable<System.DateTime> dd_thoigian { get; set; }
        public double dd_tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdondat> chitietdondats { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual trangthaidondat trangthaidondat { get; set; }
    }
}
