//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.hoadons = new HashSet<hoadon>();
            this.dondats = new HashSet<dondat>();
        }
    
        public string kh_id { get; set; }
        public string kh_username { get; set; }
        public string kh_pwd { get; set; }
        public string kh_hoten { get; set; }
        public string kh_diachi { get; set; }
        public string kh_sdt { get; set; }
        public string kh_anh { get; set; }
        public Nullable<int> kh_loai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual loaikhachhang loaikhachhang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dondat> dondats { get; set; }
    }
}
