//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public string nv_id { get; set; }
        public string nv_username { get; set; }
        public string nv_pwd { get; set; }
        public string nv_hoten { get; set; }
        public string nv_diachi { get; set; }
        public string nv_sdt { get; set; }
        public string nv_anh { get; set; }
        public Nullable<int> nv_chucvu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual chucvu chucvu { get; set; }
    }
}
