//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_555
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
            this.chitietdondats = new HashSet<chitietdondat>();
        }
    
        public int sp_id { get; set; }
        public int sp_loai { get; set; }
        public int sp_nsx { get; set; }
        public string sp_ten { get; set; }
        public double sp_gia { get; set; }
        public int sp_soluong { get; set; }
        public string sp_mota { get; set; }
        public string sp_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
        public virtual nhasanxuat nhasanxuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdondat> chitietdondats { get; set; }
    }
}
